// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";
import BackgroundGeolocation from '@mauron85/react-native-background-geolocation';

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {Big} stationaryRadius
 * @param {Big} distanceFilter
 * @param {string} url
 * @param {boolean} stopOnStillActivity
 * @param {string} runID
 * @returns {Promise.<void>}
 */
export async function Start_Tracker(stationaryRadius, distanceFilter, url, stopOnStillActivity, runID) {
	// BEGIN USER CODE
	    BackgroundGeolocation.configure({
			desiredAccuracy: BackgroundGeolocation.HIGH_ACCURACY,
			stationaryRadius: 50,
			distanceFilter: 50,
			notificationTitle: 'Run Tracker',
			notificationText: 'Background GPS enabled',
			debug: false,
			startOnBoot: false,
			stopOnTerminate: true,
			locationProvider: BackgroundGeolocation.ACTIVITY_PROVIDER,
			interval: 10000,
			fastestInterval: 5000,
			activitiesInterval: 10000,
			stopOnStillActivity: false,
			url: url+ '/tracker/location',
			runID: runID,
			httpHeaders: {
				'Content-Type': 'application/json'
			},
			// customize post properties
			postTemplate: {
				latitude: '@latitude',
				longitude: '@longitude',
				time: '@time',
				accuracy: '@accuracy',
				speed: '@speed',
				bearing: '@bearing',
				runID : runID,
			}
    });

	BackgroundGeolocation.start();
	// END USER CODE
}
